### ISSUE TITLE
Autocomplete example not working (snapshot version)

### ISSUE THREAD

**Issue by ratuka** [GwtMaterialDesign/gwt-material-demo#13]
Just open http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!autocomplete

If you start it in superdev mode, you will see something similar in the console:
    at Unknown.IndexOutOfBoundsException_1_g$(IndexOutOfBoundsException.java:25)
    at Unknown.checkIndexBoundsForInsertion_0_g$(ComplexPanel.java:152)
    at Unknown.adjustIndex_0_g$(ComplexPanel.java:117)
    at Unknown.insert_2_g$(ComplexPanel.java:192)
    at Unknown.insert_1_g$(ComplexPanel.java:182)
    at Unknown.insert_24_g$(MaterialWidget.java:632)
    at Unknown.insert_23_g$(MaterialWidget.java:103)
    at Unknown.addItem_20_g$(MaterialAutoComplete.java:387)
    at Unknown.setValue_30_g$(MaterialAutoComplete.java:655)
    at Unknown.setValue_29_g$(MaterialAutoComplete.java:647)
    at Unknown.setItemValues_0_g$(MaterialAutoComplete.java:437)
    at Unknown.AutoCompleteView_1_g$(AutoCompleteView.java:29)

**Comment by kevzlou7979** [comment]
THanks for your test, we are working on this :)

**Comment by kevzlou7979** [comment]
Fixed : https://github.com/GwtMaterialDesign/gwt-material-demo/commit/ad0878e6c2b9b31091e82e5803c253414c4c217c
