### ISSUE TITLE
Not able to run the project: Internal compiler Error

### ISSUE THREAD

**Issue by zak905** [GwtMaterialDesign/gwt-material-demo#33]
I have cloned the project and tried to run it in Super DevMode using `mvn package gwt:run`, but without any luck. Here is the stacktrace: 

```
[INFO]    [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:296)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO]  at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:67)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.visitChildren(JMethodCall.java:253)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:246)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO]  at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:351)
[INFO]  at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:145)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:600)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:569)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1505)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:870)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1305)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1038)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.precompile(JavaToJavaScriptCompiler.java:954)
[INFO]  at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.precompile(MonolithicJavaToJavaScriptCompiler.java:303)
[INFO]  at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:38)
[INFO]  at com.google.gwt.dev.Precompile.precompile(Precompile.java:286)
[INFO]  at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
[INFO]  at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
[INFO]  at com.google.gwt.dev.Compiler.run(Compiler.java:206)
[INFO]  at com.google.gwt.dev.Compiler.run(Compiler.java:158)
[INFO]  at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
[INFO]  at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO]  at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO]  at com.google.gwt.dev.Compiler.main(Compiler.java:127)
[INFO] Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
[INFO]  at org.apache.velocity.runtime.resource.ResourceManagerImpl.initialize(ResourceManagerImpl.java:161)
[INFO]  at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:730)
[INFO]  at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:263)
[INFO]  at org.apache.velocity.runtime.RuntimeInstance.requireInitialization(RuntimeInstance.java:302)
[INFO]  at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1531)
[INFO]  at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:343)
[INFO]  at com.gwtplatform.mvp.rebind.velocity.AbstractVelocityGenerator.mergeTemplate(AbstractVelocityGenerator.java:55)
[INFO]  at com.gwtplatform.mvp.rebind.velocity.ginjectors.GinjectorProviderGenerator.generate(GinjectorProviderGenerator.java:54)
[INFO]  at com.gwtplatform.mvp.rebind.velocity.GenerateFormFactorGinjectors.generateGinjectorProvider(GenerateFormFactorGinjectors.java:65)
[INFO]  at com.gwtplatform.mvp.rebind.velocity.GenerateFormFactorGinjectors.generate(GenerateFormFactorGinjectors.java:51)
[INFO]  at com.gwtplatform.mvp.rebind.GinjectorGenerator.writeFormFactors(GinjectorGenerator.java:294)
[INFO]  at com.gwtplatform.mvp.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:102)
[INFO]  at com.gwtplatform.mvp.rebind.ApplicationControllerGenerator.generate(ApplicationControllerGenerator.java:89)
[INFO]  at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
[INFO]  at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:760)
[INFO]  at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:160)
[INFO]  at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
[INFO]  at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
[INFO]  at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
[INFO]  at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:87)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:485)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:443)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:576)
[INFO]  at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:306)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:248)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  ... 46 more
[INFO] Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
[INFO]  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO]  ... 73 more
[INFO]       [ERROR] at gwt_00046material_00046design_00046demo_00046GwtMaterialDesignDemo__EntryMethodHolder.java(3): GWT.create(ApplicationController.class)
[INFO]          com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]       [ERROR] at gwt_00046material_00046design_00046demo_00046GwtMaterialDesignDemo__EntryMethodHolder.java(3): (EntryPoint) GWT.create(ApplicationController.class)
[INFO]          com.google.gwt.dev.jjs.ast.JCastOperation
[INFO]       [ERROR] at gwt_00046material_00046design_00046demo_00046GwtMaterialDesignDemo__EntryMethodHolder.java(3): ((EntryPoint) GWT.create(ApplicationController.class)).onModuleLoad()
[INFO]          com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]       [ERROR] at gwt_00046material_00046design_00046demo_00046GwtMaterialDesignDemo__EntryMethodHolder.java(3): ((EntryPoint) GWT.create(ApplicationController.class)).onModuleLoad()
[INFO]          com.google.gwt.dev.jjs.ast.JExpressionStatement
[INFO]       [ERROR] at gwt_00046material_00046design_00046demo_00046GwtMaterialDesignDemo__EntryMethodHolder.java(3): {
[INFO]   ((EntryPoint) new UserAgentAsserter()).onModuleLoad();
[INFO]   ((EntryPoint) new DocumentModeAsserter()).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(ApplicationController.class)).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(MaterialWithJQueryDebug.class)).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(MaterialDesign.class)).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(MaterialAddins.class)).onModuleLoad();
[INFO] }
[INFO]          com.google.gwt.dev.jjs.ast.JBlock
[INFO]       [ERROR] at gwt_00046material_00046design_00046demo_00046GwtMaterialDesignDemo__EntryMethodHolder.java(3): {
[INFO]   ((EntryPoint) new UserAgentAsserter()).onModuleLoad();
[INFO]   ((EntryPoint) new DocumentModeAsserter()).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(ApplicationController.class)).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(MaterialWithJQueryDebug.class)).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(MaterialDesign.class)).onModuleLoad();
[INFO]   ((EntryPoint) GWT.create(MaterialAddins.class)).onModuleLoad();
[INFO] }
[INFO]          com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]       [ERROR] at gwt_00046material_00046design_00046demo_00046GwtMaterialDesignDemo__EntryMethodHolder.java(3): public static final void init();
[INFO]
[INFO]          com.google.gwt.dev.jjs.ast.JMethod

```

**Comment by kevzlou7979** [comment]
I think this one is away too old, we can close this now.
